// 4.34 update, December 2016, by Kolbe
// Last edit: January 2019, by Kolbe
//
// This file builts the last row of the briefing.
// It is invoked just one time.

#EOL

// ----- Empt< row for html output -----
<table>



#TAB 10
<tr>
<td></td>
<td>
229
</td>
</tr>
#EOL
#EOL

#TAB 330
<tr>
<td></td>
<td></td>
<td>
#FONT 12
<h2>
256
</h2>
#ENDFONT


#EOL
#EOL
</td>
</tr>
</table>

#ENDSCRIPT
