// 4.34 update, December 2016, by Kolbe
// Last edit: January 2019, by Kolbe
//
// This file builts the SITUATION content rows.
// It is invoked multiple times to set the best targets 
// for e.g. Strikes, Seads etc. It is called by BEST_FEATURES.

///////////////////////////////////////////////////////////////
// START CONTENT ROWS
///////////////////////////////////////////////////////////////

<tr>
<td>
#TAB 30
#SPACE
185
#SPACE
ENTITY_ELEMENT_NAME
#TAB 200
185
#TAB 225
ENTITY_OPERATIONAL
164
165
#EOL
</td>
</tr>

///////////////////////////////////////////////////////////////
// END CONTENT ROWS
///////////////////////////////////////////////////////////////

#ENDSCRIPT

