// 4.34 update, December 2016, by Kolbe
// Last edit: January 2019, by Kolbe
//
// This file builts the SITUATION content rows.
// It is invoked multiple times to set the potential targets to be
// protected by BARCAP and DCA flights. It is called by POTENTIAL_TARGETS.

///////////////////////////////////////////////////////////////
// START CONTENT ROWS
///////////////////////////////////////////////////////////////

<tr>
<td>
#TAB 30
#SPACE
185
#SPACE
ENTITY_NAME
#TAB 200
185
#TAB 225
ENTITY_OPERATIONAL
164
165
#EOL
</td>
</tr>

///////////////////////////////////////////////////////////////
// END CONTENT ROWS
///////////////////////////////////////////////////////////////

#ENDSCRIPT



